// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetCare.Infrastructure.Data;

#nullable disable

namespace PetCare.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905201032_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetCare.Domain.Entities.AplicacaoVacina", b =>
                {
                    b.Property<int>("IdAplicacaoVacina")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_APLICACAO_VACINA");

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_APLICACAO");

                    b.Property<string>("Dose")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DOSE");

                    b.Property<int>("IdPet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PET");

                    b.Property<int>("IdVacina")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VACINA");

                    b.Property<int>("IdVeterinario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VETERINARIO");

                    b.Property<string>("Observacao")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("OBSERVACAO");

                    b.HasKey("IdAplicacaoVacina");

                    b.HasIndex("IdPet");

                    b.HasIndex("IdVacina");

                    b.HasIndex("IdVeterinario");

                    b.ToTable("APLICACAO_VACINA", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Clinica", b =>
                {
                    b.Property<int>("IdClinica")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NOME");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("IdClinica");

                    b.ToTable("CLINICA", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Consulta", b =>
                {
                    b.Property<int>("IdConsulta")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONSULTA");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA");

                    b.Property<int>("IdClinica")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<int>("IdPet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PET");

                    b.Property<int>("IdVeterinario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VETERINARIO");

                    b.Property<string>("Observacao")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("OBSERVACAO");

                    b.HasKey("IdConsulta");

                    b.HasIndex("IdClinica");

                    b.HasIndex("IdPet");

                    b.HasIndex("IdVeterinario");

                    b.ToTable("CONSULTA", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.HistoricoSaude", b =>
                {
                    b.Property<int>("IdHistorico")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_HISTORICO");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_REGISTRO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int>("IdConsulta")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONSULTA");

                    b.Property<int>("IdPet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PET");

                    b.HasKey("IdHistorico");

                    b.HasIndex("IdConsulta");

                    b.HasIndex("IdPet");

                    b.ToTable("HISTORICO_SAUDE", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Leitura", b =>
                {
                    b.Property<int>("IdLeitura")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LEITURA");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_REGISTRO");

                    b.Property<int>("IdSensor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SENSOR");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("VALOR");

                    b.HasKey("IdLeitura");

                    b.HasIndex("IdSensor");

                    b.ToTable("LEITURA", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Lembrete", b =>
                {
                    b.Property<int>("IdLembrete")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LEMBRETE");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int>("IdPet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PET");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TITULO");

                    b.HasKey("IdLembrete");

                    b.HasIndex("IdPet");

                    b.ToTable("LEMBRETE", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.LogErros", b =>
                {
                    b.Property<int>("IdLogErro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LOG_ERRO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLogErro"));

                    b.Property<int?>("CodigoErro")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGO_ERRO");

                    b.Property<DateTime>("DataErro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ERRO");

                    b.Property<string>("MensagemErro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("MENSAGEM_ERRO");

                    b.Property<string>("NomeProcedure")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_PROCEDURE");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("USUARIO");

                    b.HasKey("IdLogErro");

                    b.ToTable("LOG_ERROS", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Pet", b =>
                {
                    b.Property<int>("IdPet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PET");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("ESPECIE");

                    b.Property<int>("IdResponsavel")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RESPONSAVEL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)")
                        .HasColumnName("NOME");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("RACA");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("NVARCHAR2(9)")
                        .HasColumnName("SEXO");

                    b.HasKey("IdPet");

                    b.HasIndex("IdResponsavel");

                    b.ToTable("PET", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Responsavel", b =>
                {
                    b.Property<int>("IdResponsavel")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RESPONSAVEL");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("IdResponsavel");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("RESPONSAVEL", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Sensor", b =>
                {
                    b.Property<int>("IdSensor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SENSOR");

                    b.Property<int>("IdPet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PET");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("UNIDADE");

                    b.HasKey("IdSensor");

                    b.HasIndex("IdPet");

                    b.ToTable("SENSOR", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("IdUsuario");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Vacina", b =>
                {
                    b.Property<int>("IdVacina")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VACINA");

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NOME");

                    b.HasKey("IdVacina");

                    b.ToTable("VACINA", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Veterinario", b =>
                {
                    b.Property<int>("IdVeterinario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VETERINARIO");

                    b.Property<string>("CRV")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CRV");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ESPECIALIDADE");

                    b.Property<int>("IdClinica")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("IdVeterinario");

                    b.HasIndex("IdClinica");

                    b.HasIndex("IdUsuario");

                    b.ToTable("VETERINARIO", (string)null);
                });

            modelBuilder.Entity("PetCare.Domain.Entities.AplicacaoVacina", b =>
                {
                    b.HasOne("PetCare.Domain.Entities.Pet", "Pet")
                        .WithMany("AplicacoesVacina")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCare.Domain.Entities.Vacina", "Vacina")
                        .WithMany("AplicacoesVacina")
                        .HasForeignKey("IdVacina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCare.Domain.Entities.Veterinario", "Veterinario")
                        .WithMany("AplicacoesVacina")
                        .HasForeignKey("IdVeterinario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Vacina");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Consulta", b =>
                {
                    b.HasOne("PetCare.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Consultas")
                        .HasForeignKey("IdClinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCare.Domain.Entities.Pet", "Pet")
                        .WithMany("Consultas")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCare.Domain.Entities.Veterinario", "Veterinario")
                        .WithMany("Consultas")
                        .HasForeignKey("IdVeterinario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Pet");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.HistoricoSaude", b =>
                {
                    b.HasOne("PetCare.Domain.Entities.Consulta", "Consulta")
                        .WithMany("HistoricosSaude")
                        .HasForeignKey("IdConsulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCare.Domain.Entities.Pet", "Pet")
                        .WithMany("HistoricosSaude")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Leitura", b =>
                {
                    b.HasOne("PetCare.Domain.Entities.Sensor", "Sensor")
                        .WithMany("Leituras")
                        .HasForeignKey("IdSensor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Lembrete", b =>
                {
                    b.HasOne("PetCare.Domain.Entities.Pet", "Pet")
                        .WithMany("Lembretes")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Pet", b =>
                {
                    b.HasOne("PetCare.Domain.Entities.Responsavel", "Responsavel")
                        .WithMany("Pets")
                        .HasForeignKey("IdResponsavel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Responsavel", b =>
                {
                    b.HasOne("PetCare.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Responsavel")
                        .HasForeignKey("PetCare.Domain.Entities.Responsavel", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Sensor", b =>
                {
                    b.HasOne("PetCare.Domain.Entities.Pet", "Pet")
                        .WithMany("Sensores")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Veterinario", b =>
                {
                    b.HasOne("PetCare.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Veterinarios")
                        .HasForeignKey("IdClinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCare.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Veterinarios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Clinica", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("Veterinarios");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Consulta", b =>
                {
                    b.Navigation("HistoricosSaude");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Pet", b =>
                {
                    b.Navigation("AplicacoesVacina");

                    b.Navigation("Consultas");

                    b.Navigation("HistoricosSaude");

                    b.Navigation("Lembretes");

                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Responsavel", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Sensor", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Responsavel");

                    b.Navigation("Veterinarios");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Vacina", b =>
                {
                    b.Navigation("AplicacoesVacina");
                });

            modelBuilder.Entity("PetCare.Domain.Entities.Veterinario", b =>
                {
                    b.Navigation("AplicacoesVacina");

                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
